# Generated by Django 5.0.1 on 2024-03-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='user_pictures/piri.png', upload_to='media/user_pictures/'),
        ),
    ]
